### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by SingingBush** [jcgay/buildplan-maven-plugin#29]
It's been a while since 1.3 and now the code is updated for maven 3.6.*

any chance of a new release?

**Comment by jcgay** [comment]
There is no functional change since `v1.3`, do you have a problem with Maven `3.6.x` ?
All the new commits are about build dependencies, it should not change the plugin behavior.

Thx 😇

**Comment by SingingBush** [comment]
no issue with 3.6.x, I use latest release for all builds. Just noticed warn messages in build log about a plugin referencing pom.version instead of project.version which appeared immediately after build plan initialised so suspected it's due to this plugin and thought that a version targeting more recent maven may clear it.

In general I don't want my maven plugins to have new behaviour. I just want them all to support latest maven and most recent Java releases, which is getting harder recently.

**Comment by jcgay** [comment]
I don't think this particular message comes from this plugin but let me know it is 😅.
